format="$username@$hostname $directory( $git_branch)( $python)\\$ " 

[username]
disabled=false
show_always=true
style_user="green"
format="[$user]($style)"

[hostname]
disabled=false
ssh_only=false
style="green"
format="[$hostname]($style)"

[directory]
format="[$path]($style)"

[git_branch]
disabled=false
symbol=""
style="bold yellow"
always_show_remote=true
format="[$branch $symbol]($style)"

[git_commit]

[python]
format="[$virtualenv]($style)"
